enum recr_area_codes {
    FRAME_MGMT                  = 0,  // Shooting frame management
    CPU_PROC                    = 1,  // CPU processing
    WB_FINE_ADJ                 = 2,  // White balance fine adjustment computation
    MULTI_FRAME_PROC            = 3,  // Multi-frame processing
    STP_PROC                    = 4,  // STP processing
    STRING_EMBED_PROC           = 5,  // String embedding processing
    CCDIF                       = 6,  // CCDIF (CCD interface?)
    PFP_SCRATCH_CORR            = 7,  // PFP (scratch correction)
    IFP_PHASE_CORR              = 8,  // IFP (phase difference correction)
    RECC                        = 9,  // RECC
    DCN                         = 10, // DCN
    RESZ                        = 11, // Resize processing
    JPEG                        = 12, // JPEG encoding/processing
    RETCH                       = 13, // RETCH (retouch?)
    ROT                         = 14, // Rotation processing
    TCUBE                       = 15, // TCUBE
    TCUBE_PR                    = 16, // TCUBE-PR
    MEDIA                       = 17, // Media handling
    DMA                         = 18, // Direct Memory Access? 
    REMOTE_WLAN_AREA            = 19, // Remote shooting WLAN area
    REMOTE_LIVEVIEW_COMP_AREA   = 20, // Remote shooting live-view compression area
    EXPOSURE_CAPTURE_AREA            = 21,  // Exposure capture area
    UNUSED_1                         = 22,  // Unused
    FLASH_INFO_STORAGE               = 23,  // Flash/exposure control info storage area
    FACE_OFFSET_CORR_WORK            = 24,  // Face offset correction work area
    FACE_AWB_WORK                    = 25,  // Face AWB calculation work area
    RAW_YC                           = 26,  // RAW YC area
    MAIN_YC                          = 27,  // Main YC area
    UNUSED_7                         = 28,  // Unused
    RAF_THUMB_YC_WORK                = 29,  // RAF thumbnail work YC
    ZOOM_NAV_DISPLAY                 = 30,  // Zoom navigation image display area
    BURST_PREVIEW_VGA                = 31,  // Burst preview (2x2) for VGA output
    DISPLAY_IMAGE                    = 32,  // Display image area
    YC_MULTI_STAGE_WORK              = 33,  // YC multi-stage work area
    MAIN_COMP_MIN                    = 34,  // Main compression (minimum size)
    INTERNAL_COMP_WORK               = 35,  // Internal compression work area
    STRING_EMBED_WORK                = 36,  // String embedding work area
    AUTO_DEBUG_INFO                  = 37,  // Auto debug info area
    INTERNAL_YC                      = 38,  // Internal YC area
    UNUSED_18                        = 39,  // Unused
    BURST_PREVIEW_XGA                = 40,  // Burst preview (2x2) for XGA output
    KB_DVS_SIGNAL_WORK               = 41,  // KB/DVS signal processing work area
    UNUSED_EXR_21                    = 42,  // Unused (EXR-only area)
    UNUSED_EXR_22                    = 43,  // Unused (EXR-only area)
    EX1_EXPOSURE_CAPTURE             = 44,  // EX1 exposure capture area
    EX2_EXPOSURE_CAPTURE             = 45,  // EX2 exposure capture area
    UNUSED_25                        = 46,  // Unused
    UNUSED_26                        = 47,  // Unused
    UNUSED_27                        = 48,  // Unused
    BOKEH_PARAM_AREA                 = 49,  // Bokeh parameter area
    DCN_RECYC_RESIZED                = 50,  // DCN recorded YC resized area
    DCN_RAWYC_YC_AFTER_DIST_REF      = 51,  // DCN RAWYC YC after distance image (reference image)
    DCN_RAWYC_DST_AFTER_DIST_REF     = 52,  // DCN RAWYC DST after distance image (reference image)
    DCN_RAWYC_YC_AFTER_DIST          = 53,  // DCN RAWYC YC after distance image
    DCN_RAWYC_DST_AFTER_DIST         = 54,  // DCN RAWYC DST after distance image
    DCN_RAWYC_RETCH_AFTER            = 55,  // DCN RAWYC after retouch
    DCN_RAWYC_YC_AFTER               = 56,  // DCN RAWYC YC after
    DCN_RAWYC_DST_AFTER              = 57,  // DCN RAWYC DST after
    DCN_RAWYC_BOKEH_ENH_AFTER        = 58,  // DCN RAWYC after bokeh enhancement
    YC_QUARTER                       = 59,  // 1/4 YC area
    YC_SIXTEENTH                     = 60,  // 1/16 YC area
    DCN_PR_HIER_ALL                  = 61,  // DCN PR processing hierarchical image area (all)
    DIST_IMAGE_AREA                  = 62,  // Distance image area
    INTERFRAME_SHARED_DATA           = 63,  // Inter-frame shared data area
    SP_COORD_DATA                    = 64,  // SP coordinate data area
    TP_COORD_DATA                    = 65,  // TP coordinate data area
    GME_WORK                         = 66,  // GME work area
    DIS_RECYC_RESIZED                = 67,  // DIS recorded YC resized area
    DIS_RAWYC_YC_AFTER_REF           = 68,  // DIS RAWYC YC after (reference image)
    DIS_RAWYC_YC_AFTER               = 69,  // DIS RAWYC YC after
    DIS_RAWYC_RETCH_AFTER            = 70,  // DIS RAWYC after retouch
    DIS_RAWYC_DCN_COMPOSITE          = 71,  // DIS RAWYC after DCN composite
    DIS_RAWYC_YC_NR_AFTER             = 72,  // DIS RAWYC after YC noise reduction
    DIS_RAWYC_DCN_COMPOSITE_REF       = 73,  // DIS RAWYC after DCN composite (reference image)
    DIS_RAWYC_YC_POSTPROC_AFTER       = 74,  // DIS RAWYC after YC post-processing
    TP_COORD_DATA_2                   = 75,  // TP coordinate data area
    SP_COORD_DATA_2                   = 76,  // SP coordinate data area
    DIS_PR_HIER_ALL                   = 77,  // DIS PR processing hierarchical image area (all)
    GME_WORK_2                        = 78,  // GME work area
    INTERFRAME_SHARED_DATA_2          = 79,  // Inter-frame shared data area
    COMPOSITE_MAD_DATA                = 80,  // Composite MAD data area
    COMPOSITE_MAP_DATA                = 81,  // Composite MAP data area
    RED_EYE_FULL_YC                   = 82,  // Red-eye correction overall YC
    RED_EYE_FACE_YC1                  = 83,  // Red-eye correction face YC1
    RED_EYE_FACE_YC2                  = 84,  // Red-eye correction face YC2
    RED_EYE_FACE_YC3                  = 85,  // Red-eye correction face YC3
    RED_EYE_FACE_YC4                  = 86,  // Red-eye correction face YC4
    RED_EYE_MODULE_WORK               = 87,  // Red-eye correction module work area
    EXPOSURE_CAPTURE_AREA_2           = 94,  // Exposure capture area
    FLASH_INFO_STORAGE_2              = 96,  // Flash/exposure control info storage area
    FACE_OFFSET_CORR_WORK_2           = 97,  // Face offset correction work area
    FACE_AWB_WORK_2                   = 98,  // Face AWB calculation work area
    RAW_YC_2                          = 99,  // RAW YC area
    MAIN_YC_2                         = 100, // Main YC area
    RAF_THUMB_YC_WORK_2               = 102, // RAF thumbnail work YC
    ZOOM_NAV_DISPLAY_2                = 103, // Zoom navigation image display area
    DISPLAY_IMAGE_2                   = 105, // Display image area
    YC_MULTI_STAGE_WORK_2             = 106, // YC multi-stage work area
    MAIN_COMP_MIN_2                   = 107, // Main compression (minimum size)
    INTERNAL_COMP_WORK_2              = 108, // Internal compression work area
    STRING_EMBED_WORK_2               = 109, // String embedding work area
    AUTO_DEBUG_INFO_2                 = 110, // Auto debug info area
    INTERNAL_YC_2                     = 111, // Internal YC area
    KB_DVS_SIGNAL_WORK_2              = 114, // KB/DVS signal processing work area
    ADVF_MAP_DATA                     = 118, // Advanced filter map data
    MAIN_YC_3                         = 119, // Main YC area
    MAIN_YC_4                         = 120,  // Main YC area
    ADVF_DCN_YC                     = 121, // Advanced filter DCN processing YC
    MAIN_YC_5                       = 122, // Main YC area
    ADVF_DCN_YC_2                   = 123, // Advanced filter DCN processing YC
    MAIN_YC_6                       = 124, // Main YC area
    YC_SUPERLOW_RES                 = 125, // Super low resolution YC
    YC_ULTRALOW_FREQ_MAP_LUMA       = 126, // Ultra-low frequency map (luminance only)
    YC_ULTRALOW_FREQ_INTERMEDIATE   = 127, // Ultra-low frequency intermediate YC
    ADVF_HIER_IMAGE_ALL             = 128, // Advanced filter hierarchical image area (all)
    GP_EXPOSURE_CAPTURE             = 167, // GP exposure capture area
    GP_RAW_YC                       = 172, // GP RAW YC area
    GP_MAIN_YC                      = 173, // GP main YC area
    INTERNAL_YC_3                   = 174, // Internal YC area
    DISPLAY_IMAGE_3                 = 178, // Display image area
    GP_YC_MULTI_STAGE               = 179, // GP YC multi-stage work area
    GP_MAIN_COMP_PANORAMA           = 180, // GP main compression area (panorama image)
    INTERNAL_COMP_WORK_3            = 181, // Internal compression work area
    AUTO_DEBUG_INFO_3               = 183, // Auto debug info area
    GP_MAIN_YC_ROTATED              = 184, // GP main YC area (after rotation)
    GP_TEMPLATE_MATCH_YC_QUARTER    = 185, // GP template matching 1/4 YC area
    KB_DVS_SIGNAL_WORK_3            = 186, // KB/DVS signal processing work area
    GP_PANORAMA_YC_BUFFERED         = 187, // GP panorama YC area (after buffering)
    GP_PANORAMA_YC_TRIM_ROTATED     = 188, // GP panorama YC area (after trim & rotation)
    GP_SGP_YC_QUARTER_1             = 189, // GP SGP 1/4 YC area
    GP_SGP_YC_QUARTER_2             = 190, // GP SGP 1/4 YC area
    GP_TP_COORD_DATA                = 191, // GP TP coordinate data area
    GP_SP_COORD_DATA                = 194, // GP SP coordinate data area
    GP_SGP_WARP_YC                  = 195, // GP SGP warping image YC area
    GP_SGP_WARP_AFFINE_PARAMS       = 196, // GP SGP warping affine parameter data area
    GP_SGP_KEYMAP_DATA              = 197, // GP SGP keymap data area
    GP_SGP_LEFT_YC_COMPOSITE        = 198, // GP SGP left image YC (for warp composite)
    GP_SGP_LEFT_YC_HORIZ_CORR       = 199, // GP SGP left image YC (horizontal correction output)
    GP_SGP_RIGHT_YC_HORIZ_CORR      = 200, // GP SGP right image YC (horizontal correction output)
    GP_SGP_COMPOSITE_BUFFER_YC      = 201, // GP SGP composite buffer YC
    GP_SGP_MAIN_YC_RESIZED          = 202, // GP SGP main image YC (resize output)
    GP_SGP_MAIN_YC_ROTATED          = 203, // GP SGP main image YC (rotated output)
    GP_SGP_MAIN_COMP_PANORAMA       = 204, // GP SGP main compression area (panorama image)
    GP_SGP_PR_HIER_IMAGE_ALL        = 205, // GP SGP PR processing hierarchical image area (all)
    GP_YC_MULTI_STAGE_2             = 207, // GP YC multi-stage work area
    INTERNAL_COMP_WORK_4            = 209, // Internal compression work area
    GP_SGP_TP_IMAGE_COPIED          = 210, // GP SGP TP image area (after copy)
    GP_SGP_SP_IMAGE_COPIED          = 211, // GP SGP SP image area (after copy)
    JIG_EXPOSURE_CAPTURE_1          = 240, // Jig exposure capture area
    FLASH_INFO_STORAGE_3            = 242, // Flash/exposure control info storage area
    JIG_EXPOSURE_CAPTURE_2          = 245, // Jig exposure capture area
    AUTO_DEBUG_INFO_4               = 256, // Auto debug info area
    KB_DVS_SIGNAL_WORK_4            = 260, // KB/DVS signal processing work area
    JIG_EXPOSURE_CAPTURE_3          = 313, // Jig exposure capture area
    AUTO_DEBUG_INFO_5               = 329, // Auto debug info area
    EXPOSURE_CAPTURE_AREA_3         = 386, // Exposure capture area
    FLASH_INFO_STORAGE_4            = 388, // Flash/exposure control info storage area
    MV_RAW_YC                       = 391, // MV RAW YC area
    MAIN_YC_7                       = 392, // Main YC area
    YC_MULTI_STAGE_WORK_3           = 398, // YC multi-stage work area
    MAIN_COMP_MAX_VIDEO_STILL       = 399, // Main compression (max size: still in video)
    INTERNAL_COMP_WORK_5            = 400, // Internal compression work area
    STRING_EMBED_WORK_3             = 401, // String embedding work area
    INTERNAL_YC_4                   = 403, // Internal YC area
    KB_DVS_SIGNAL_WORK_5            = 406, // KB/DVS signal processing work area
    EXPOSURE_CAPTURE_AREA_4         = 459, // Exposure capture area
    FLASH_INFO_STORAGE_5            = 461, // Flash/exposure control info storage area
    MV_RAW_YC_2                     = 464, // MV RAW YC area
    MAIN_YC_8                       = 465, // Main YC area
    YC_MULTI_STAGE_WORK_4           = 471, // YC multi-stage work area
    MAIN_COMP_MAX_VIDEO_STILL_2     = 472, // Main compression (max size: still in video)
    INTERNAL_COMP_WORK_6            = 473, // Internal compression work area
    STRING_EMBED_WORK_4             = 474, // String embedding work area
    INTERNAL_YC_5                   = 476, // Internal YC area
    KB_DVS_SIGNAL_WORK_6            = 479, // KB/DVS signal processing work area
    FLASH_INFO_STORAGE_6            = 534, // Flash/exposure control info storage area
    YC_MULTI_STAGE_WORK_5           = 544, // YC multi-stage work area
    MAIN_COMP_MAX_VIDEO_STILL_3     = 545, // Main compression (max size: still in video)
    INTERNAL_COMP_WORK_7            = 546, // Internal compression work area
    STRING_EMBED_WORK_5             = 547, // String embedding work area
    INTERNAL_YC_6                   = 549, // Internal YC area
    FLASH_INFO_STORAGE_7            = 607, // Flash/exposure control info storage area
    YC_MULTI_STAGE_WORK_6           = 617, // YC multi-stage work area
    MAIN_COMP_MAX_VIDEO_STILL_4     = 618, // Main compression (max size: still in video)
    INTERNAL_COMP_WORK_8            = 619, // Internal compression work area
    STRING_EMBED_WORK_6             = 620, // String embedding work area
    INTERNAL_YC_7                   = 622, // Internal YC area
    EXPOSURE_CAPTURE_AREA_5         = 678, // Exposure capture area
    RAW_YC_3                        = 683, // RAW YC area
    MAIN_YC_RAW_DEV                 = 684, // Main YC area (for RAW development)
    RAF_THUMB_YC_WORK_3             = 686, // RAF thumbnail work YC
    DISPLAY_IMAGE_4                 = 689, // Display image area
    YC_MULTI_STAGE_WORK_7           = 690, // YC multi-stage work area
    MAIN_COMP_MAX                   = 691, // Main compression (max size)
    INTERNAL_COMP_WORK_9            = 692, // Internal compression work area
    AUTO_DEBUG_INFO_6               = 694, // Auto debug info area
    INTERNAL_YC_8                   = 695, // Internal YC area
    KB_DVS_SIGNAL_WORK_7            = 698,  // KB/DVS signal processing work area
};
