//MODE_FOCUS
enum MODE_FOCUS {
MODE_FOCUS_MF=0x0,
MODE_FOCUS_AF_MULTI=0x1,
MODE_FOCUS_AF_AREA_SELECT=0x2,
MODE_FOCUS_AF_ZONE=0x3,
MODE_FOCUS_AF_CENTER=0x4,
MODE_FOCUS_CAF_MULTI=0x5,
MODE_FOCUS_CAF_AREA_SELECT=0x6,
MODE_FOCUS_CAF_ZONE=0x7,
MODE_FOCUS_CAF_CENTER=0x8,
MODE_FOCUS_MOVE_CHASE=0x9,
MODE_FOCUS_NUM=0xa
};
