enum RECCF_ACT_CODE {
    Q_SACLA_StillCapture_Exposure                     = 0x00, // 静止画撮影_露光 -- Still image capture (exposure)
    Q_SACLA_StillCaptureDone_Exposure                 = 0x01, // 静止画撮影完了_露光 -- Still image capture complete (exposure)
    Q_SACLA_StillCapture_Shielded                     = 0x02, // 静止画撮影_遮光 -- Still image capture (dark/shielded)
    Q_SACLA_StillCaptureDone_Shielded                 = 0x03, // 静止画撮影完了_遮光 -- Still image capture complete (dark/shielded)
    Q_SACLA_MakeDisplayImage                          = 0x04, // 表示画像作成 -- Generate display image
    Q_SACLA_MakeDisplayImage_Resp                     = 0x05, // 表示画像作成応答 -- Display image generation response
    I_SACLA_StopExposure_S2Off                        = 0x06, // 露光停止_S2OFF -- Stop exposure (S2 released)
    I_SACLA_StopExposure_PowerOff                     = 0x07, // 露光停止_電源OFF -- Stop exposure (power off)
    Q_SACLA_StopStillCapture                          = 0x08, // 静止画撮影停止 -- Stop still capture
    Q_SACLA_StopStillCapture_Done                     = 0x09, // 静止画撮影停止完了 -- Still capture stop complete
    RCV_SACLA_StillCaptureStart_Exposure              = 0x0A, // 静止画撮影開始_露光 -- Still capture start (exposure)
    RCV_SACLA_StillCaptureStart_Shielded              = 0x0B, // 静止画撮影開始_遮光 -- Still capture start (dark/shielded)
    RCV_SACLA_ExposureComplete                        = 0x0C, // 露光完了 -- Exposure complete
    RCV_SACLA_PlaybackImageMade                       = 0x0D, // 取り込み再生画像作成完了 -- Imported/playback image creation complete
    RCV_SACLA_ImportDone_Main_Exposure                = 0x0E, // 取込み完了_主画素_露光 -- Import complete (main pixels, exposure)
    RCV_SACLA_ImportDone_Main_Shielded                = 0x0F, // 取込み完了_主画素_遮光 -- Import complete (main pixels, dark)
    RCV_SACLA_ImportDone_Sub_Exposure                 = 0x10, // 取込み完了_副画素_露光 -- Import complete (sub pixels, exposure)
    RCV_SACLA_ImportDone_Sub_Shielded                 = 0x11, // 取込み完了_副画素_遮光 -- Import complete (sub pixels, dark)
    RCV_SACLA_StillCaptureDone_Exposure               = 0x12, // 静止画撮影完了_露光 -- Still image capture complete (exposure)
    RCV_SACLA_StillCaptureDone_Shielded               = 0x13, // 静止画撮影完了_遮光 -- Still image capture complete (dark)
    RCV_SACLA_AWBComplete_Exposure                    = 0x14, // AWB演算完了_露光 -- AWB calculation complete (exposure)
    RCV_SACLA_AWBComplete_Shielded                    = 0x15, // AWB演算完了_遮光 -- AWB calculation complete (dark)

    Q_BKLIST_PFP_Request_Main_Exposure                = 0x16, // 処理要求_主画素_露光 -- PFP (defect fix) request (main, exposure)
    Q_BKLIST_PFP_Response_Main_Exposure               = 0x17, // 処理応答_主画素_露光 -- PFP response (main, exposure)
    Q_BKLIST_PFP_Request_Main_Shielded                = 0x18, // 処理要求_主画素_遮光 -- PFP request (main, dark)
    Q_BKLIST_PFP_Response_Main_Shielded               = 0x19, // 処理応答_主画素_遮光 -- PFP response (main, dark)
    Q_BKLIST_PFP_Request_Sub_Exposure                 = 0x1A, // 処理要求_副画素_露光 -- PFP request (sub, exposure)
    Q_BKLIST_PFP_Response_Sub_Exposure                = 0x1B, // 処理応答_副画素_露光 -- PFP response (sub, exposure)
    Q_BKLIST_PFP_Request_Sub_Shielded                 = 0x1C, // 処理要求_副画素_遮光 -- PFP request (sub, dark)
    Q_BKLIST_PFP_Response_Sub_Shielded                = 0x1D, // 処理応答_副画素_遮光 -- PFP response (sub, dark)
    Q_BKLIST_IFP_Request_Main                         = 0x1E, // IFP_処理要求_主画素 -- IFP (phase) request (main)
    Q_BKLIST_IFP_Response_Main                        = 0x1F, // IFP_処理応答_主画素 -- IFP response (main)
    Q_BKLIST_IFP_Request_Sub                          = 0x20, // IFP_処理要求_副画素 -- IFP request (sub)
    Q_BKLIST_IFP_Response_Sub                         = 0x21, // IFP_処理応答_副画素 -- IFP response (sub)
    Q_BKLIST_STP_Request_LateDefect                   = 0x22, // STP_処理要求_後発キズ -- STP request (late defects)
    Q_BKLIST_STP_Response_LateDefect                  = 0x23, // STP_処理応答_後発キズ -- STP response (late defects)
    Q_BKLIST_CPU_Request                              = 0x24, // CPU_処理要求 -- CPU processing request
    Q_BKLIST_CPU_Response                             = 0x25, // CPU_処理応答 -- CPU processing response
    Q_BKLIST_CPU_Request_Drain_Main                   = 0x26, // CPU_処理要求_ドレイン_主画素 -- CPU request (drain, main)
    Q_BKLIST_CPU_Response_Drain_Main                  = 0x27, // CPU_処理応答_ドレイン_主画素 -- CPU response (drain, main)
    Q_BKLIST_CPU_Request_Drain_Sub                    = 0x28, // CPU_処理要求_ドレイン_副画素 -- CPU request (drain, sub)
    Q_BKLIST_CPU_Response_Drain_Sub                   = 0x29, // CPU_処理応答_ドレイン_副画素 -- CPU response (drain, sub)
    Q_BKLIST_CPU_Request_EmbedString_Postview         = 0x2A, // CPU_処理要求_文字列埋め込み_ポストビュー -- CPU request (embed string, postview)
    Q_BKLIST_CPU_Response_EmbedString_Postview        = 0x2B, // CPU_処理応答_文字列埋め込み_ポストビュー -- CPU response (embed string, postview)
    Q_BKLIST_CPU_Request_BlackFill                    = 0x2C, // CPU_処理要求_黒塗り -- CPU request (black fill/masking)
    Q_BKLIST_CPU_Response_BlackFill                   = 0x2D, // CPU_処理応答_黒塗り -- CPU response (black fill/masking)
    Q_BKLIST_RECC_Request                             = 0x2E, // RECC_処理要求 -- RECC pipeline request
    Q_BKLIST_RECC_Response                            = 0x2F, // RECC_処理応答 -- RECC pipeline response
    Q_BKLIST_RECC_PreprocRequest                      = 0x30, // RECC_前処理要求 -- RECC pre-processing request
    Q_BKLIST_RECC_PreprocResponse                     = 0x31, // RECC_前処理応答 -- RECC pre-processing response
    Q_BKLIST_RECC_Request_BlackLevel_Main             = 0x32, // RECC_処理要求_黒引き_主画素 -- RECC black-level subtract request (main)
    Q_BKLIST_RECC_Response_BlackLevel_Main            = 0x33, // RECC_処理応答_黒引き_主画素 -- RECC black-level subtract response (main)
    Q_BKLIST_RECC_Request_BlackLevel_Sub              = 0x34, // RECC_処理要求_黒引き_副画素 -- RECC black-level subtract request (sub)
    Q_BKLIST_RECC_Response_BlackLevel_Sub             = 0x35, // RECC_処理応答_黒引き_副画素 -- RECC black-level subtract response (sub)
    Q_BKLIST_RESZ_Request_Pre                         = 0x36, // RESZ_処理要求_処理前 -- Resize request (before)
    Q_BKLIST_RESZ_Response_Pre                        = 0x37, // RESZ_処理応答_処理前 -- Resize response (before)
    Q_BKLIST_RESZ_Request_Post                        = 0x38, // RESZ_処理要求_処理後 -- Resize request (after)
    Q_BKLIST_RESZ_Response_Post                       = 0x39, // RESZ_処理応答_処理後 -- Resize response (after)
    Q_BKLIST_RESZ_Request_MakeFaceRegImage            = 0x3A, // RESZ_処理要求_顔登録画像作成 -- Resize request (face registration image)
    Q_BKLIST_RESZ_Response_MakeFaceRegImage           = 0x3B, // RESZ_処理応答_顔登録画像作成 -- Resize response (face registration image)
    Q_BKLIST_JPEG_CompressReq_Pre                     = 0x3C, // JPEG_圧縮要求_処理前 -- JPEG compress request (before)
    Q_BKLIST_JPEG_CompressResp_Pre                    = 0x3D, // JPEG_圧縮応答_処理前 -- JPEG compress response (before)
    Q_BKLIST_JPEG_CompressReq_Post                    = 0x3E, // JPEG_圧縮要求_処理後 -- JPEG compress request (after)
    Q_BKLIST_JPEG_CompressResp_Post                   = 0x3F, // JPEG_圧縮応答_処理後 -- JPEG compress response (after)
    Q_BKLIST_JPEG_CompressReq_RAF                     = 0x40, // JPEG_圧縮要求_RAF -- JPEG compress request (RAF embedded)
    Q_BKLIST_JPEG_CompressResp_RAF                    = 0x41, // JPEG_圧縮応答_RAF -- JPEG compress response (RAF embedded)
    Q_BKLIST_JPEG_CompressReq_JFIF                    = 0x42, // JPEG_圧縮要求_JFIF -- JPEG compress request (JFIF)
    Q_BKLIST_JPEG_CompressResp_JFIF                   = 0x43, // JPEG_圧縮応答_JFIF -- JPEG compress response (JFIF)
    Q_BKLIST_MEDIA_RecordReq_Pre                      = 0x44, // メディア記録要求_処理前 -- Media record request (before)
    Q_BKLIST_MEDIA_RecordResp_Pre                     = 0x45, // メディア記録応答_処理前 -- Media record response (before)
    Q_BKLIST_MEDIA_RecordReq_Post                     = 0x46, // メディア記録要求_処理後 -- Media record request (after)
    Q_BKLIST_MEDIA_RecordResp_Post                    = 0x47, // メディア記録応答_処理後 -- Media record response (after)
    Q_BKLIST_MEDIA_RecordReq_RAF                      = 0x48, // メディア記録要求_RAF -- Media record request (RAF)
    Q_BKLIST_MEDIA_RecordResp_RAF                     = 0x49, // メディア記録応答_RAF -- Media record response (RAF)
    Q_BKLIST_MEDIA_DCFCC_ProcReq_Pre                  = 0x4A, // DCFCC_メディア処理要求_処理前 -- DCF/DCF-C proc request (before)
    Q_BKLIST_MEDIA_DCFCC_ProcResp_Pre                 = 0x4B, // DCFCC_メディア処理応答_処理前 -- DCF/DCF-C proc response (before)
    Q_BKLIST_MEDIA_DCFCC_ProcReq_Post                 = 0x4C, // DCFCC_メディア処理要求_処理後 -- DCF/DCF-C proc request (after)
    Q_BKLIST_MEDIA_DCFCC_ProcResp_Post                = 0x4D, // DCFCC_メディア処理応答_処理後 -- DCF/DCF-C proc response (after)
    Q_BKLIST_MEDIA_DCFCC_ProcReq_RAF                  = 0x4E, // DCFCC_メディア処理要求_RAF -- DCF/DCF-C proc request (RAF)
    Q_BKLIST_MEDIA_DCFCC_ProcResp_RAF                 = 0x4F, // DCFCC_メディア処理応答_RAF -- DCF/DCF-C proc response (RAF)
    Q_BKLIST_DCN_YCCompositeReq                       = 0x50, // DCN_YC合成処理要求 -- DCN YC composite request
    Q_BKLIST_DCN_YCCompositeResp                      = 0x51, // DCN_YC合成処理応答 -- DCN YC composite response
    Q_BKLIST_ALL_RedEyeCorrectionReq                  = 0x52, // ALL_赤目補正処理要求 -- Red-eye correction request
    Q_BKLIST_ALL_RedEyeCorrectionResp                 = 0x53, // ALL_赤目補正処理応答 -- Red-eye correction response
    Q_BKLIST_RESZ_DSTReq                              = 0x54, // RESZ_DST処理要求 -- Distortion resize request
    Q_BKLIST_RESZ_DSTResp                             = 0x55, // RESZ_DST処理応答 -- Distortion resize response
    Q_BKLIST_RESZ_DSTReq_Depth                        = 0x56, // RESZ_DST処理要求_距離画像用 -- DST resize request (depth image)
    Q_BKLIST_RESZ_DSTResp_Depth                       = 0x57, // RESZ_DST処理応答_距離画像用 -- DST resize response (depth)
    Q_BKLIST_RECC_YCConvertReq_Depth                  = 0x58, // RECC_YC変換処理要求_距離画像用 -- YC convert request (depth)
    Q_BKLIST_RECC_YCConvertResp_Depth                 = 0x59, // RECC_YC変換処理応答_距離画像用 -- YC convert response (depth)
    Q_BKLIST_ALL_BokehParamCalcReq                    = 0x5A, // ALL_ボケパラメータ算出処理要求 -- Bokeh parameter calc request
    Q_BKLIST_ALL_BokehParamCalcResp                   = 0x5B, // ALL_ボケパラメータ算出処理応答 -- Bokeh parameter calc response
    Q_BKLIST_TCUBE_PR_Make1Over16YCReq                = 0x5C, // TCUBE_PR_処理要求_1/16YC作成 -- TCUBE-PR make 1/16 YC request
    Q_BKLIST_TCUBE_PR_Make1Over16YCResp               = 0x5D, // TCUBE_PR_処理応答_1/16YC作成 -- TCUBE-PR make 1/16 YC response
    Q_BKLIST_TCUBE_PR_BokehEmphasisReq                = 0x5E, // TCUBE_PR_処理要求_ボケ強調用 -- TCUBE-PR for bokeh emphasis request
    Q_BKLIST_TCUBE_PR_BokehEmphasisResp               = 0x5F, // TCUBE_PR_処理応答_ボケ強調用 -- TCUBE-PR for bokeh emphasis response
    Q_BKLIST_DCN_MakeDepthImageReq                    = 0x60, // DCN_距離画像作成処理要求 -- Make depth image request
    Q_BKLIST_DCN_MakeDepthImageResp                   = 0x61, // DCN_距離画像作成処理応答 -- Make depth image response
    Q_BKLIST_DCN_BokehEmphasisReq                     = 0x62, // DCN_ボケ強調処理要求 -- DCN bokeh emphasis request
    Q_BKLIST_DCN_BokehEmphasisResp                    = 0x63, // DCN_ボケ強調処理応答 -- DCN bokeh emphasis response
    Q_BKLIST_TCUBE_PR_Request                         = 0x64, // TCUBE_PR_処理要求 -- TCUBE-PR processing request
    Q_BKLIST_TCUBE_PR_Response                        = 0x65, // TCUBE_PR_処理応答 -- TCUBE-PR processing response
    Q_BKLIST_TCUBE_Request                            = 0x66, // TCUBE_処理要求 -- TCUBE processing request
    Q_BKLIST_TCUBE_Response                           = 0x67, // TCUBE_処理応答 -- TCUBE processing response
    Q_BKLIST_ALL_GetTransformInfoReq                  = 0x68, // ALL_画像変形情報取得処理要求 -- Get image transform info request
    Q_BKLIST_ALL_GetTransformInfoResp                 = 0x69, // ALL_画像変形情報取得処理応答 -- Get image transform info response
    Q_BKLIST_RETCH_TransformReq                       = 0x6A, // RETCH_処理要求_画像変形 -- RETCH transform request
    Q_BKLIST_RETCH_TransformResp                      = 0x6B, // RETCH_処理応答_画像変形 -- RETCH transform response
    Q_BKLIST_DCN_Request                              = 0x6C, // DCN_処理要求 -- DCN processing request
    Q_BKLIST_DCN_Response                             = 0x6D, // DCN_処理応答 -- DCN processing response
    Q_BKLIST_DCN_Request_FinalImage                   = 0x6E, // DCN_処理要求_最終画像 -- DCN request (final image)
    Q_BKLIST_DCN_Response_FinalImage                  = 0x6F, // DCN_処理応答_最終画像 -- DCN response (final image)
    Q_BKLIST_RECC_NRReq                               = 0x70, // RECC_処理要求_NR処理 -- RECC noise reduction request
    Q_BKLIST_RECC_NRResp                              = 0x71, // RECC_処理応答_NR処理 -- RECC noise reduction response
    Q_BKLIST_RECC_PostProcReq_Pre                     = 0x72, // RECC_処理要求_後処理_処理前 -- RECC post-proc request (before)
    Q_BKLIST_RECC_PostProcResp_Pre                    = 0x73, // RECC_処理応答_後処理_処理前 -- RECC post-proc response (before)
    Q_BKLIST_RECC_PostProcReq_Post                    = 0x74, // RECC_処理要求_後処理_処理後 -- RECC post-proc request (after)
    Q_BKLIST_RECC_PostProcResp_Post                   = 0x75, // RECC_処理応答_後処理_処理後 -- RECC post-proc response (after)
    Q_BKLIST_ALL_AdvFilterReq                         = 0x76, // ALL_ADVフィルタ処理要求 -- Advanced filter request
    Q_BKLIST_ALL_AdvFilterResp                        = 0x77, // ALL_ADVフィルタ処理応答 -- Advanced filter response
    Q_BKLIST_DMA_BitmaskYCReq_1st                     = 0x78, // DMA_ビットマスクYC作成処理要求_1回目 -- Make YC bitmask request (1st)
    Q_BKLIST_DMA_BitmaskYCResp_1st                    = 0x79, // DMA_ビットマスクYC作成処理応答_1回目 -- Make YC bitmask response (1st)
    Q_BKLIST_DMA_BitmaskYCReq_2nd                     = 0x7A, // DMA_ビットマスクYC作成処理要求_2回目 -- Make YC bitmask request (2nd)
    Q_BKLIST_DMA_BitmaskYCResp_2nd                    = 0x7B, // DMA_ビットマスクYC作成処理応答_2回目 -- Make YC bitmask response (2nd)
    Q_BKLIST_ALL_SweepPanoramaMakeReq                 = 0x7C, // ぐるっとパノラマ画像作成処理要求 -- Sweep panorama image make request
    Q_BKLIST_ALL_SweepPanoramaMakeResp                = 0x7D, // ぐるっとパノラマ画像作成処理応答 -- Sweep panorama image make response
    Q_BKLIST_ALL_SweepPanoramaSaveReq                 = 0x7E, // ぐるっとパノラマ合成保存処理要求 -- Sweep panorama composite save request
    Q_BKLIST_ALL_SweepPanoramaSaveResp                = 0x7F, // ぐるっとパノラマ合成保存処理応答 -- Sweep panorama composite save response
    Q_BKLIST_ALL_AddRAWReq                            = 0x80, // ALL_RAW加算処理要求 -- RAW add/accumulate request
    Q_BKLIST_ALL_AddRAWResp                           = 0x81, // ALL_RAW加算処理応答 -- RAW add/accumulate response

    I_WLAN_PostviewTransfer                           = 0x82, // 無線LAN_ポストビュー画転送 -- WLAN postview image transfer
    N_WLAN_PostviewTransferDone                       = 0x83, // 無線LAN_ポストビュー画転送完了 -- WLAN postview transfer complete
    RCV_YCConvertDone_Main                            = 0x84, // YC変換処理完了_本画像 -- YC conversion complete (main image)
    RCV_YCConvertDone_PixelMixed                      = 0x85, // YC変換処理完了_画素混 -- YC conversion complete (pixel-mixed)
    RCV_ResizeDone_Pre                                = 0x86, // リサイズ完了_処理前 -- Resize complete (before)
    RCV_CompressDone_EmbeddedJPEG_Pre                 = 0x87, // 圧縮完了_内包JPEG_処理前 -- Compression complete (embedded JPEG, before)
    RCV_CompressDone_EmbeddedJPEG_Post                = 0x88, // 圧縮完了_内包JPEG_処理後 -- Compression complete (embedded JPEG, after)
    RCV_CompressDone_Thumb_RAF                        = 0x89, // 圧縮完了_サムネイル_RAF -- Compression complete (RAF thumbnail)
    RCV_MediaRecordStart_Pre                          = 0x8A, // メディア記録開始_処理前 -- Media record start (before)
    RCV_MediaRecordStart_Post                         = 0x8B, // メディア記録開始_処理後 -- Media record start (after)
    RCV_MediaRecordStart_RAF                          = 0x8C, // メディア記録開始_RAF -- Media record start (RAF)
    RCV_MediaRecordDone_Pre                           = 0x8D, // メディア記録完了_処理前 -- Media record complete (before)
    RCV_MediaRecordDone_Post                          = 0x8E, // メディア記録完了_処理後 -- Media record complete (after)
    RCV_MediaRecordDone_RAF                           = 0x8F, // メディア記録完了_RAF -- Media record complete (RAF)
    RCV_RedEyeDetectStartNotice                       = 0x90, // 赤目検出開始通知 -- Red-eye detection start notice
    RCV_RedEyeDetectDoneNotice                        = 0x91, // 赤目検出完了通知 -- Red-eye detection complete notice
    RCV_FaceRegDisplayImageDone                       = 0x92, // 顔登録表示画像作成完了 -- Face registration display image complete
    RCV_LowFreqMapDone                                = 0x93, // 低周波マップ作成完了 -- Low-frequency map creation complete
    RCV_IntegratedDiffImageDone                       = 0x94, // 統合差分画像作成完了 -- Integrated difference image creation complete

    I_ReleaseWait_SubRECC_PermitWait                  = 0x95, // 待ち解除_許可待ち_副画素RECC -- Release wait (permit wait, sub-pixel RECC)
    I_ReleaseWait_PixelMixYC_PermitWait               = 0x96, // 待ち解除_許可待ち_画素混YC作成 -- Release wait (permit wait, pixel-mix YC)
    I_ReleaseWait_MainCompressDoneWait                = 0x97, // 待ち解除_本画像圧縮完了待ち -- Release wait (main image compression done)
    I_ReleaseWait_RedEyeCorrectionPermitWait          = 0x98, // 待ち解除_赤目補正許可待ち -- Release wait (red-eye correction permit)
    I_ReleaseWait_FaceRecogResultWait                 = 0x99, // 待ち解除_顔認識結果取得完了待ち -- Release wait (face recognition result)
    I_S2CompleteWait                                  = 0x9A, // S2完了待ち -- Wait for S2 complete
    I_TemplateMatchPermitWait                         = 0x9B, // テンプレートマッチング許可待ち -- Template matching permit wait
    I_SmoothingPermitWait                             = 0x9C, // スムージング許可待ち -- Smoothing permit wait
    I_WBComputePermitWait                             = 0x9D, // 許可待ち_WB演算 -- Wait permit for WB compute
    I_ReleaseWait_AdvF_1                              = 0x9E, // 待ち解除_許可待ち_ADVF_1 -- Release wait (Advanced Filter 1)
    I_ReleaseWait_AdvF_2                              = 0x9F, // 待ち解除_許可待ち_ADVF_2 -- Release wait (Advanced Filter 2)
    I_AllFramesPreprocDone                            = 0xA0, // 前後撮り全コマ前処理完了 -- Preproc done for all frames (pre/post)

    N_SVOUT_ProcDone                                  = 0xA1, // SVOUT_処理完了 -- Processing complete
    N_SVOUT_S2Started                                 = 0xA2, // SVOUT_S2開始済み -- S2 already started
    N_SVOUT_MFStillDone                               = 0xA3, // SVOUT_MF時静止画撮影完了 -- MF still capture complete
    N_SVOUT_ShieldedS2Start                           = 0xA4, // SVOUT_遮光S2開始 -- Shielded S2 start
    N_SVOUT_S2Done                                    = 0xA5, // SVOUT_S2完了 -- S2 complete
    N_SVOUT_MFCompositeDone                           = 0xA6, // SVOUT_MF撮影画像合成完了 -- MF capture image composite complete
    N_SVOUT_LiveViewResumePermit                      = 0xA7, // SVOUT_スルー画復帰許可 -- Permit live-view resume
    N_SVOUT_ReleasePermit                             = 0xA8, // SVOUT_レリーズ許可 -- Release permitted
    N_SVOUT_S1Permit                                  = 0xA9, // SVOUT_S1許可 -- S1 permitted
    N_SVOUT_ChargePermit                              = 0xAA, // SVOUT_充電許可 -- Charging permitted
    N_SVOUT_RecordChargePermit                        = 0xAB, // SVOUT_記録充電許可 -- Record charging permitted
    N_SVOUT_ShootingError                             = 0xAC, // SVOUT_撮影エラー発生 -- Shooting error occurred
    N_SVOUT_DisplayImageDone                          = 0xAD, // SVOUT_表示画像作成完了 -- Display image made
    N_SVOUT_BackgroundImageDone                       = 0xAE, // SVOUT_背景画像作成完了 -- Background image made
    N_SVOUT_RedEyeDetectStart                         = 0xAF, // SVOUT_赤目検出開始 -- Red-eye detect start
    N_SVOUT_RedEyeDetectDone                          = 0xB0, // SVOUT_赤目検出完了 -- Red-eye detect done
    N_SVOUT_RedEyeCorrectionDone                      = 0xB1, // SVOUT_赤目補正完了 -- Red-eye correction done
    N_SVOUT_BurstFirstFrameStart                      = 0xB2, // SVOUT_連写1コマ撮影開始 -- Burst first-frame start
    N_SVOUT_BurstEnd                                  = 0xB3, // SVOUT_連写撮影終了 -- Burst shooting ended
    N_SVOUT_MFEnd                                     = 0xB4, // SVOUT_MF撮影終了 -- MF shooting end
    N_SVOUT_MovieEnd                                  = 0xB5, // SVOUT_動画撮影終了 -- Movie recording end
    N_SVOUT_MovieOpticalZoomPermit                    = 0xB6, // SVOUT_動画光学ズーム駆動許可通知 -- Movie optical-zoom drive permitted
    N_SVOUT_MovieInterval                             = 0xB7, // SVOUT_動画インターバル -- Movie interval
    N_SVOUT_MoviePaused                               = 0xB8, // SVOUT_動画中断 -- Movie interrupted
    N_SVOUT_FaceRecStartPermit_S2                     = 0xB9, // SVOUT_顔認識開始許可_S2 -- Face recognition start permit (S2)
    N_SVOUT_FaceRegStartPermit                        = 0xBA, // SVOUT_顔認識開始許可_顔登録 -- Face recognition start permit (registration)
    N_SVOUT_BurstStopFixTiming                        = 0xBB, // SVOUT_連写停止確定タイミング通知 -- Burst stop fixed-timing notice
    N_SVOUT_StillStartTiming                          = 0xBC, // SVOUT_静止画撮影開始タイミング通知 -- Still-capture start timing
    N_SVOUT_ExposureDoneTiming                        = 0xBD, // SVOUT_露光完了タイミング通知 -- Exposure done timing
    N_SVOUT_RecordProcDone                            = 0xBE, // SVOUT_記録処理完了 -- Record processing done
    N_SVOUT_PanoramaSynthesisStart                    = 0xBF, // SVOUT_ぐるっとパノラマ合成開始 -- Sweep panorama synthesis start
    N_SVOUT_SeamlessPanoramaFailed                    = 0xC0, // SVOUT_ぐるっとシームレスパノラマ合成失敗 -- Seamless panorama synthesis failed
    N_SVOUT_FaceRegImageDone                          = 0xC1, // SVOUT_顔登録画像作成完了 -- Face registration image done
    N_SVOUT_MyLandmarkImageDone                       = 0xC2, // SVOUT_マイランドマーク登録画像作成完了 -- My-landmark reg image done
    N_SVOUT_QuickPlayPermit                           = 0xC3, // SVOUT_すぐ再生許可 -- Quick playback permitted
    N_SVOUT_MediaWriteStart                           = 0xC4, // SVOUT_メディア書込み開始 -- Media write start
    N_SVOUT_MediaWriteDone                            = 0xC5, // SVOUT_メディア書込み完了 -- Media write complete

    RCV_StopExposureCmd_S2Off                         = 0xC6, // 露光停止指示_S2OFF -- Stop exposure command (S2 off)
    RCV_StopExposureCmd_PowerOff                      = 0xC7, // 露光停止指示_電源OFF -- Stop exposure command (power off)
    RCV_SignalProcStartPermit                         = 0xC8, // 信号処理開始許可通知 -- Signal processing start permitted
    RCV_MakeCaptureDisplayImage                       = 0xC9, // 撮影表示画像作成指示 -- Make capture display image
    RCV_UpdateCaptureDisplayPermit                    = 0xCA, // 撮影表示画像更新許可指示 -- Update capture display image permitted
    RCV_FaceRecognitionResult                         = 0xCB, // 顔認識結果通知 -- Face recognition result
    RCV_S2RecognitionResult                           = 0xCC, // S2認識結果通知 -- S2 recognition result
    RCV_LiveViewResumeDone                            = 0xCD, // スルー画復帰完了通知 -- Live-view resume complete
    RCV_BurstStopCommand                              = 0xCE, // 連写撮影停止指示 -- Burst shooting stop command
    RCV_BurstAbortCommand                             = 0xCF, // 連写撮影中止指示 -- Burst shooting abort command
    RCV_BurstPreviewUpdatePermit                      = 0xD0, // 連写プレビュー更新許可指示 -- Burst preview update permit
    RCV_MediaRecordPermit                             = 0xD1, // メディア記録許可通知 -- Media recording permitted
    RCV_RedEyeDetectAbort                             = 0xD2, // 赤目検出中断指示 -- Red-eye detection abort
    RCV_RedEyeCorrectionEnd                           = 0xD3, // 赤目補正終了指示 -- Red-eye correction end
    RCV_RedEyeCorrectionStart                         = 0xD4, // 赤目補正開始指示 -- Red-eye correction start
    RCV_MultipleExposureSaveStart                     = 0xD5, // 多重露出撮影保存開始指示 -- Multiple-exposure save start
    RCV_StillRecordResume                             = 0xD6, // 静止画記録再開通知 -- Still image recording resume

    Q_EXTERNAL_FaceDetect                             = 0xD7, // 顔検出 -- Face detection
    Q_EXTERNAL_FaceDetect_Done                        = 0xD8, // 顔検出_完了 -- Face detection complete
    Q_EXTERNAL_FPSControlTimer                        = 0xD9, // FPS制御タイマー -- FPS control timer
    Q_EXTERNAL_FPSControlTimer_Done                   = 0xDA, // FPS制御タイマー_完了 -- FPS control timer complete

    Q_OTHER_DisplayImage_Preview                      = 0xDB, // 表示画像_プレビュー -- Display image (preview)
    Q_OTHER_DisplayImage_Preview_Done                 = 0xDC, // 表示画像_プレビュー_完了 -- Display image (preview) complete
    Q_OTHER_DisplayImage_Background                   = 0xDD, // 表示画像_背景画像 -- Display image (background)
    Q_OTHER_DisplayImage_Background_Done              = 0xDE, // 表示画像_背景画像完了 -- Display image (background) complete
    Q_OTHER_Preview                                   = 0xDF, // プレビュー -- Preview
    Q_OTHER_Preview_Done                              = 0xE0, // プレビュー_完了 -- Preview complete
    Q_OTHER_PersonalRecognition                       = 0xE1, // 個人認識 -- Personal recognition
    Q_OTHER_PersonalRecognition_Done                  = 0xE2, // 個人認識_完了 -- Personal recognition complete
    I_OTHER_SaveSACLAInfo                             = 0xE3, // SACLA情報保持 -- Keep SACLA info
    I_OTHER_Reserve_RAW                               = 0xE4, // リソース予約_RAW -- Reserve resources (RAW)
    I_OTHER_Reserve_JPEG_Pre                          = 0xE5, // リソース予約_JPEG_処理前 -- Reserve resources (JPEG, before)
    I_OTHER_Reserve_JPEG_RAF                          = 0xE6, // リソース予約_JPEG_RAF -- Reserve resources (JPEG, RAF)
    I_OTHER_FrameEnd                                  = 0xE7, // コマ終了 -- Frame end

    STS_State_InputAreaFree                           = 0xE8, // 処理状態_取り込み領域空き -- Input/import area free
    STS_State_S2CycleEnd                              = 0xE9, // 処理状態_S2サイクル終了 -- S2 cycle end
    STS_InProc_S2_Exposure                            = 0xEA, // 処理中_S2_露光 -- In processing S2 (exposure)
    STS_InProc_S2_Shielded                            = 0xEB, // 処理中_S2_遮光 -- In processing S2 (dark)

    CTRL_OtherFrameDepend_None                        = 0xEC, // 別コマ依存_無し -- No inter-frame dependency
    CTRL_OtherFrameDepend_Pre                         = 0xED, // 別コマ依存_前処理 -- Depends on other frame (pre)
    CTRL_OtherFrameDepend_Post                        = 0xEE, // 別コマ依存_後処理 -- Depends on other frame (post)
    CTRL_OtherFrameTrigger_On                         = 0xEF, // 別コマ開始トリガ_ON -- Other-frame start trigger ON
    CTRL_OtherFrameTrigger_Off                        = 0xF0, // 別コマ開始トリガ_OFF -- Other-frame start trigger OFF
    CTRL_OrderGuarantee_Off                           = 0xF1, // 順序保証_OFF -- No ordering guarantee
    CTRL_OrderGuarantee_CPU                           = 0xF2, // 順序保証_CPU -- Order guarantee: CPU
    CTRL_OrderGuarantee_ChargePermit                  = 0xF3, // 順序保証_充電許可 -- Order guarantee: charging permit
    CTRL_OrderGuarantee_YCConvert                     = 0xF4, // 順序保証_YC変換 -- Order guarantee: YC convert
    CTRL_OrderGuarantee_Compress                      = 0xF5, // 順序保証_圧縮 -- Order guarantee: compression
    CTRL_OrderGuarantee_MediaRecord                   = 0xF6, // 順序保証_メディア記録 -- Order guarantee: media record
    CTRL_OrderGuarantee_GetResource_JPEG              = 0xF7, // 順序保証_リソース取得_JPEG -- Order guarantee: acquire JPEG resource
    CTRL_NotExecuted                                  = 0xF8, // 未実施 -- Not executed
    CTRL_ConditionalMsgUpdate                         = 0xF9, // 条件付MSG更新 -- Conditional message update

    ActionTypeCount                                   = 0xFA, // アクション種別数 -- Number of action types
    ActionStatusArrayCount                            = 0xFB, // アクション実施状況配列数 -- Action-status array count
    RECCF_CTRL_END_MARKER                             = 0xFC, // (END MARKER)
};

